apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: "main"
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git:v2.49.1
      script: |
        #!/bin/sh
        set -e
        git clone --single-branch --branch $(params.revision) $(params.repo-url) $(workspaces.output.path)
