server:
  port: 0 # random port

spring:
  application:
    name: user-service
  profiles:
    group:
      default: oauth
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    show-sql: true
  cache:
    jcache:
      config: classpath:ehcache.xml

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
  health:
    mail:
      enabled: false
