version: '3'
services:
  userservice:
    container_name: userservice
    image: egovframe/msa-user-service:latest
    restart: always
    volumes:
      - ${HOME}/workspace:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TZ: Asia/Seoul

  boardservice:
    container_name: boardservice
    image: egovframe/msa-board-service:latest
    restart: always
    volumes:
      - ${HOME}/workspace:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      EUREKA_INSTANCE_HOSTNAME: discovery
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      MYSQL_HOSTNAME: mysql
      TZ: Asia/Seoul

  portalservice:
    container_name: portalservice
    image: egovframe/msa-portal-service:latest
    restart: always
    volumes:
      - ${HOME}/workspace:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      EUREKA_INSTANCE_HOSTNAME: discovery
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      MYSQL_HOSTNAME: mysql
      TZ: Asia/Seoul

networks:
  default:
    external:
      name: egov-network