apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    env: production
    tier: backend
    app: discovery
    name: discovery-service
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    env: production
    tier: backend
    app: discovery
    name: discovery-pod