spring:
  r2dbc:
    url: r2dbc:mysql://${mysql.hostname:localhost}:3306/msaportal?serverTimezone=Asia/Seoul
    username: msaportal
    password: msaportal
cloud:
  stream:
    function:
      definition: reserveRequest # 예약 요청후 물품 재고업데이트 이벤트에 대한 consumer function
    bindings:
      reserveRequest-in-0: # 예약 요청후 물품 재고업데이트 이벤트에 대한 consumer binding
        destination: reserve-request.topic # queue name
        group: reserved
      inventoryUpdated-out-0: # 예약 요청후 물품 재고업데이트 결과에 이벤트에 대한 supplier binding
        destination: inventory-updated.topic # queue name
        group: reserved
