apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: npm-build
spec:
  workspaces:
    - name: source
  steps:
    - name: install-and-build
      image: node:18-alpine
      workingDir: $(workspaces.source.path)/frontend/portal
      env:
        - name: NODE_OPTIONS
          value: "--openssl-legacy-provider"
      script: |
        #!/bin/sh
        npm ci
        npm run build
