apiVersion: v1
kind: Service
metadata:
  name: apigateway
  labels:
    env: production
    tier: backend
    app: apigateway
    name: apigateway-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    env: production
    tier: backend
    app: apigateway
    name: apigateway-pod